"""
SQLAlchemy models for the operator assignment invitation domain.

This module contains the database model for tracking staff invitations generated by
landlords to invite new caretakers/operators to manage a lodge.
"""
from datetime import datetime, timezone
import uuid
from typing import TYPE_CHECKING, Optional

from sqlalchemy import ForeignKey, DateTime, String, func
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.enums import OperatorInviteStatus
from app.db.session import Base

if TYPE_CHECKING:
    from app.models.lodge import Lodge
    from app.models.user import User


class OperatorInvite(Base):
    """
    SQLAlchemy model representing an operator assignment invitation.

    Attributes:
        id: Primary key UUID for the invitation.
        lodge_id: Foreign key referencing the lodge to be managed.
        created_by_user_id: Foreign key referencing the user who sent the invite.
        target_phone_no: The phone number of the intended operator (phone-locked).
        status: Stored status (None = ACTIVE, human-set = ACCEPTED/APPROVED/REJECTED).
                EXPIRED is computed when expires_at has passed.
        accepted_by_user_id: Foreign key referencing the operator user who accepted (SET NULL on delete).
        expires_at: Timestamp when the invite expires.
        created_at: Timestamp when the invite was generated.
    """
    __tablename__ = 'operator_invites'

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid7)
    lodge_id: Mapped[int] = mapped_column(ForeignKey('lodges.id', ondelete='CASCADE'), nullable=False)
    created_by_user_id: Mapped[int] = mapped_column(ForeignKey('users.id', ondelete='CASCADE'), nullable=False)
    target_phone_no: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    status: Mapped[Optional[OperatorInviteStatus]] = mapped_column(
        SQLEnum(OperatorInviteStatus),
        nullable=True  # NULL means no action yet (invite is active by default)
    )
    accepted_by_user_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey('users.id', ondelete='SET NULL'),
        nullable=True
    )
    expires_at: Mapped[datetime] = mapped_column(nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )

    lodge: Mapped["Lodge"] = relationship(back_populates='operator_invites')
    created_by_landlord: Mapped["User"] = relationship(foreign_keys=[created_by_user_id])
    # No back_populates — this is a one-directional read from the invite to the user who accepted.
    accepted_by_operator: Mapped[Optional["User"]] = relationship(foreign_keys=[accepted_by_user_id])

    @property
    def lodge_name(self) -> str:
        return self.lodge.name if self.lodge else "N/A"

    @property
    def created_by_landlord_name(self) -> str:
        if self.created_by_landlord:
            return f"{self.created_by_landlord.first_name} {self.created_by_landlord.last_name}"
        return "N/A"

    @property
    def computed_status(self) -> OperatorInviteStatus:

        """
        Derive the effective status without writing a cron job or touching the DB.
        Priority: time (EXPIRED) > stored status > default ACTIVE.
        """
        if self.status is not None:
            return self.status
        curr_time = datetime.now(timezone.utc).replace(tzinfo=None)
        if curr_time > self.expires_at:
            return OperatorInviteStatus.EXPIRED
        return OperatorInviteStatus.ACTIVE


