"""
SQLAlchemy models for the lodge ownership invitation domain.

This module contains the database model for tracking ownership invitations generated by
caretakers/operators for landlords to claim legal title of a lodge.
"""
from datetime import datetime, timezone
import uuid
from typing import TYPE_CHECKING, Optional

from sqlalchemy import ForeignKey, DateTime, String, func
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.enums import OwnershipInviteStatus
from app.db.session import Base

if TYPE_CHECKING:
    from app.models.lodge import Lodge
    from app.models.user import User


class OwnershipInvite(Base):
    """
    SQLAlchemy model representing an ownership claim invitation.

    Attributes:
        id: Primary key UUID for the invitation.
        lodge_id: Foreign key referencing the unclaimed lodge.
        created_by_user_id: Foreign key referencing the operator who generated the invite.
        target_phone_no: The expected landlord phone number locked to this claim.
        status: Current status (ACTIVE, CONSUMED, EXPIRED).
        claimed_by_user_id: Foreign key referencing the landlord who claimed ownership.
        expires_at: Timestamp when the invite expires.
        created_at: Timestamp when the invite was generated.
    """
    __tablename__ = 'ownership_invites'

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid7)
    lodge_id: Mapped[int] = mapped_column(ForeignKey('lodges.id', ondelete='CASCADE'), nullable=False)
    created_by_user_id: Mapped[int] = mapped_column(ForeignKey('users.id', ondelete='CASCADE'), nullable=False)
    target_phone_no: Mapped[str] = mapped_column(String(20), nullable=False)
    status: Mapped[Optional[OwnershipInviteStatus]] = mapped_column(
        SQLEnum(OwnershipInviteStatus),
        nullable=True  # NULL means not yet consumed or expired — effectively ACTIVE
    )
    claimed_by_user_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey('users.id', ondelete='SET NULL'),
        nullable=True
    )
    expires_at: Mapped[datetime] = mapped_column(nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False
    )

    lodge: Mapped["Lodge"] = relationship(back_populates='ownership_invites')
    created_by_operator: Mapped["User"] = relationship(foreign_keys=[created_by_user_id])
    claimed_by_landlord: Mapped[Optional["User"]] = relationship(foreign_keys=[claimed_by_user_id])

    @property
    def lodge_name(self) -> str:
        return self.lodge.name if self.lodge else "N/A"

    @property
    def created_by_operator_name(self) -> str:
        if self.created_by_operator:
            return f"{self.created_by_operator.first_name} {self.created_by_operator.last_name}"
        return "N/A"

    @property
    def computed_status(self) -> OwnershipInviteStatus:

        """
        Derive effective status without a cron job.
        Priority: time (EXPIRED) > stored status (CONSUMED) > default ACTIVE.
        """
        if self.status is not None:
            return self.status
        curr_time = datetime.now(timezone.utc).replace(tzinfo=None)
        if curr_time > self.expires_at:
            return OwnershipInviteStatus.EXPIRED
        return OwnershipInviteStatus.ACTIVE

