"""add_operator_and_ownership_support

Revision ID: 220040393ee8
Revises: 2a3b4c5d6e7f
Create Date: 2026-08-29 22:01:39.946686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220040393ee8'
down_revision: Union[str, Sequence[str], None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lodge_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'REVOKED', name='operatorstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lodge_id', 'operator_id', name='uq_lodge_operator')
    )
    op.create_table('operator_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACCEPTED', 'APPROVED', 'REJECTED', 'EXPIRED', name='operatorinvitestatus'), nullable=False),
    sa.Column('accepted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ownership_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lodge_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('target_phone_no', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONSUMED', 'EXPIRED', name='ownershipinvitestatus'), nullable=False),
    sa.Column('claimed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lodges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.alter_column('landlord_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_lodges_created_by_user_id', 'users', ['created_by_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_lodges_landlord_id', 'users', ['landlord_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lodges', schema=None) as batch_op:
        batch_op.alter_column('landlord_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_by_user_id')

    op.drop_table('ownership_invites')
    op.drop_table('operator_invites')
    op.drop_table('lodge_operators')

    # ### end Alembic commands ###
